---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
        - name: svc2
          image: thedevelopnik/nodesvc2:1.3
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  selector:
    app: svc2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081