---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
        - name: svc1
          image: thedevelopnik/nodesvc1:1.2
          ports:
            - containerPort: 8080
          env:
            - name: SVC2_ADDR
              value: svc2.default:8081
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  selector:
    app: svc1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080